name:  CI-CD __ DevOps

on:
  push:
    branches: [ main ]

jobs:
        
  build:
    name: Build 
    runs-on: ubuntu-latest
    steps:
        - run: echo CONSTRUINDO O SOFTWARE NO AMBIENTE DE DEV
      
  deploy-dev:
    name: Teste em DEV
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - run: echo REALIZANDO TESTES UNITARIOS
      
  testing-qa:
    name: Mover código para QA e Testar
    needs: [deploy-dev]
    runs-on: ubuntu-latest
    steps:
      - run: echo MOVENDO E TESTES DE INTEGRACAO EM AMBIENTE QA
        
  deploy-stage:
    name: Mover para STAGE
    needs: [testing-qa]
    runs-on: ubuntu-latest
    steps:
      - run: echo MOVENDO PARA AMBIENTE DE PRE-PRODUCAO
      
  deploy-production:
    name: Lançar software em Produção
    needs: [deploy-stage]
    runs-on: ubuntu-latest
    steps:
      - run: echo LANCAMENTO DO SOFTWARE
